import "~/styles/globals.css";
import { cookies } from "next/headers";
import { TRPCReactProvider } from "~/trpc/react";
import { ThemeProvider } from "./_components/ThemeProvider";
import { inter } from "../common/lib/fonts";
import { NextAuthProvider } from "./_components/AuthProvider";
import { cn } from "../common/lib/utils";
import { Toaster } from "react-hot-toast";
import ReduxProvider from "./_components/ReduxProvider";
import Layout from "./_components/layout";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("relative font-sans antialiased", inter.className)}>
        <NextAuthProvider>
          <TRPCReactProvider cookies={cookies().toString()}>
            <ReduxProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                <Layout>{children}</Layout>
                <Toaster />
              </ThemeProvider>
            </ReduxProvider>
          </TRPCReactProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
